; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_build.arduino.partitions = default_16MB.csv

monitor_speed = 115200
upload_speed = 460800

lib_deps =
  lvgl/lvgl@^9.2.2
  ESP32Async/ESPAsyncWebServer
  ESP32Async/AsyncTCP
  bblanchon/ArduinoJson@^7.0.0

build_flags =
  -D BOARD_HAS_PSRAM                 ; Enable PSRAM support for the ESP32-S3 board
  -D CORE_DEBUG_LEVEL=3              ; Set the Arduino core log level to informational messages
  -D ARDUINO_USB_MODE=1              ; Use the native USB mode
  -D ARDUINO_USB_CDC_ON_BOOT=1       ; Enable the USB CDC serial port at boot
  -D LV_CONF_INCLUDE_SIMPLE          ; Allow LVGL to find lv_conf.h without a path prefix